redo the way we look for tcl so it doesn't use AC_CHECK_FILE (which fails on cross-compilation), and merge the checks for the .h with the checks for the library function so we're sure we get consistent settings.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -860,7 +860,8 @@ Optional Packages:
   --with-target=TARGET    use target TARGET (default native)
   --with-cc=CC            name (or path) of the C compiler to use
   --with-tcl=DIR          location of a tcl installation (default system)
-  --with-tclver=VERSION   tcl version to use (default $ac_tclver)
+  --with-tcldir=DIR       same as --with-tcl
+  --with-tclver=VERSION   tcl version to use (default $ac_tclvers)
   --with-db=DIR           location of a Berkeley DB installation (default
                           system)
   --with-dbver=VERSION    Berkeley DB versions to try (default $ac_dbver)
@@ -2937,8 +2938,7 @@ _ACEOF
 fi
 
 
-
-    ac_tclver='8.4 8.3'
+    ac_tclvers='8.4 8.3'
     ac_tcldir='system'
 
 
@@ -2949,96 +2949,66 @@ if test "${with_tcl+set}" = set; then
 fi;
 
 
-# Check whether --with-tclver or --without-tclver was given.
-if test "${with_tclver+set}" = set; then
-  withval="$with_tclver"
-  ac_tclver=$withval
+# Check whether --with-tcldir or --without-tcldir was given.
+if test "${with_tcldir+set}" = set; then
+  withval="$with_tcldir"
+  ac_tcldir=$withval
 fi;
 
 
-    if test x$oasys_cv_path_tcl_h = x ; then
-        echo "checking for tcl header file..."
+# Check whether --with-tclver or --without-tclver was given.
+if test "${with_tclver+set}" = set; then
+  withval="$with_tclver"
+  ac_tclvers=$withval
+fi;
 
-  if test "${oasys_cv_path_tcl_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
+                if test $ac_tcldir = no ; then
+       { { echo "$as_me:$LINENO: error: cannot configure without tcl" >&5
+echo "$as_me: error: cannot configure without tcl" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+                if test ! x$oasys_cv_path_tcl_h = x ; then
+        echo "checking for tcl installation... (cached) \
+	      ($oasys_cv_path_tcl_h/tcl.h, $oasys_cv_path_tcl_lib -l$oasys_cv_lib_tcl)"
+    else
 
     oasys_cv_path_tcl_h=
+
+    ac_save_CPPFLAGS="$CPPFLAGS"
+    ac_save_LDFLAGS="$LDFLAGS"
+    ac_save_LIBS="$LIBS"
 
     if test ! x"$ac_tcldir" = x"system" ; then
         ac_tclincdirs=$ac_tcldir/include/
     else
         ac_tclincdirs="/usr/include /usr/local/include"
-	for tclver in $ac_tclver ; do
-           ac_tclincdirs="$ac_tclincdirs /usr/include/tcl$tclver"
+	for ac_tclver in $ac_tclvers ; do
+           ac_tclincdirs="$ac_tclincdirs /usr/include/tcl$ac_tclver"
         done
     fi
 
-    for ac_tclincdir in $ac_tclincdirs; do
-        as_ac_File=`echo "ac_cv_file_$ac_tclincdir/tcl.h" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $ac_tclincdir/tcl.h" >&5
-echo $ECHO_N "checking for $ac_tclincdir/tcl.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$ac_tclincdir/tcl.h"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  oasys_cv_path_tcl_h=$ac_tclincdir; break
-fi
-
-    done
-
-fi
-
-
-  if test x$oasys_cv_path_tcl_h = x ; then
-        { { echo "$as_me:$LINENO: error: can't find usable tcl.h" >&5
-echo "$as_me: error: can't find usable tcl.h" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
+    if test x"$ac_tcldir" = x"system" ; then
+        ac_tcllibdirs="/usr/lib"
     else
-        echo "checking for tcl header... (cached) $oasys_cv_path_tcl_h"
+        ac_tcllibdirs="$ac_tcldir/lib"
     fi
 
-    if test ! $oasys_cv_path_tcl_h = /usr/include ; then
-        CPPFLAGS="$CPPFLAGS -I$oasys_cv_path_tcl_h"
-    fi
+    for ac_tclver in $ac_tclvers ; do
+    for ac_tclincdir in $ac_tclincdirs; do
+    for ac_tcllibdir in $ac_tcllibdirs; do
+    for ac_tcllib in tcl tcl$ac_tclver; do
 
+        echo "$as_me:$LINENO: checking for tcl (version $ac_tclver) in $ac_tclincdir, $ac_tcllibdir, -l$ac_tcllib" >&5
+echo $ECHO_N "checking for tcl (version $ac_tclver) in $ac_tclincdir, $ac_tcllibdir, -l$ac_tcllib... $ECHO_C" >&6
 
-    if test ! x"$ac_tcldir" = x"system" ; then
-        LDFLAGS="$LDFLAGS -L$ac_tcldir/lib"
-    fi
+        ac_tclver_major=`echo $ac_tclver | cut -d . -f1`
+	ac_tclver_minor=`echo $ac_tclver | cut -d . -f2`
+	CPPFLAGS="$ac_save_CPPFLAGS -I$ac_tclincdir"
+	LDFLAGS="$ac_save_LDFLAGS -I$ac_tcllibdir"
+	LIBS="$ac_save_LIBS -l$ac_tcllib"
 
-    if test x$oasys_cv_lib_tcl = x ; then
-        echo "checking for tcl library..."
-
-    if test "${oasys_cv_lib_tcl+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-        for tclver in "" $ac_tclver; do
-            oasys_cv_lib_tcl=tcl$tclver
-            as_ac_Lib=`echo "ac_cv_lib_$oasys_cv_lib_tcl''_Tcl_Init" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for Tcl_Init in -l$oasys_cv_lib_tcl" >&5
-echo $ECHO_N "checking for Tcl_Init in -l$oasys_cv_lib_tcl... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Lib+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-l$oasys_cv_lib_tcl  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
+	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -3046,17 +3016,19 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char Tcl_Init ();
+                #include <tcl.h>
+
+                #if (TCL_MAJOR_VERSION != ${ac_tclver_major}) || \
+                    (TCL_MINOR_VERSION != ${ac_tclver_minor})
+                #error "incorrect version"
+                #endif
+
 int
 main ()
 {
-Tcl_Init ();
+
+                Tcl_Interp* interp = Tcl_CreateInterp();
+
   ;
   return 0;
 }
@@ -3073,37 +3045,47 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  eval "$as_ac_Lib=yes"
+
+              echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+              oasys_cv_path_tcl_h=$ac_tclincdir
+              oasys_cv_path_tcl_lib=$ac_tcllibdir
+              oasys_cv_lib_tcl=$ac_tcllib
+              break 4
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-eval "$as_ac_Lib=no"
+
+              echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
-if test `eval echo '${'$as_ac_Lib'}'` = yes; then
-  break
-else
-  oasys_cv_lib_tcl=
-fi
+    done
+    done
+    done
+    done
 
-        done
+    CPPFLAGS="$ac_save_CPPFLAGS"
+    LDFLAGS="$ac_save_LDFLAGS"
+    LIBS="$ac_save_LIBS"
 
-fi
-
-
-    if test x$oasys_cv_lib_tcl = x ; then
-        { { echo "$as_me:$LINENO: error: can't find usable tcl library" >&5
-echo "$as_me: error: can't find usable tcl library" >&2;}
+    if test x$oasys_cv_path_tcl_h = x ; then
+        { { echo "$as_me:$LINENO: error: can't find usable tcl.h" >&5
+echo "$as_me: error: can't find usable tcl.h" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
-    else
-        echo "checking for tcl library... (cached) $oasys_cv_lib_tcl"
+    fi
+
+    if test ! $oasys_cv_path_tcl_h = /usr/include ; then
+        CPPFLAGS="$CPPFLAGS -I$oasys_cv_path_tcl_h"
+    fi
+
+    if test ! $oasys_cv_path_tcl_lib = /usr/lib ; then
+        LDFLAGS="$LDFLAGS -L$oasys_cv_path_tcl_lib"
     fi
 
     LIBS="$LIBS -l$oasys_cv_lib_tcl"
