add a test for a broken implementation of std::string::reserve(). gcc 3.1 on my mac is unfortunately subject to this one :-(

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2637,6 +2637,7 @@ fi
 
 
 
+
     echo "$as_me:$LINENO: checking for the version of the gcc compiler" >&5
 echo $ECHO_N "checking for the version of the gcc compiler... $ECHO_C" >&6
 if test "${oasys_cv_prog_gccver+set}" = set; then
@@ -2740,6 +2741,95 @@ echo "${ECHO_T}$oasys_cv_prog_gcc_w_no_long_double" >&6
 
     if test $oasys_cv_prog_gcc_w_no_long_double = yes ; then
         OASYS_CPPFLAGS="$OASYS_CPPFLAGS -Wno-long-double"
+    fi
+
+    echo "$as_me:$LINENO: checking whether std::string::reserve() is broken" >&5
+echo $ECHO_N "checking whether std::string::reserve() is broken... $ECHO_C" >&6
+if test "${oasys_cv_prog_gcc_string_broken+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+        ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+        if test "$cross_compiling" = yes; then
+
+              oasys_cv_prog_gcc_string_broken=maybe
+
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+               #include <string>
+
+int
+main ()
+{
+
+                std::string s;
+                s.reserve(1);
+                try {
+                    s.replace(0, 1, "X", 1);
+                } catch(...) {
+                    exit(1);
+                }
+                exit(0);
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+              oasys_cv_prog_gcc_string_broken=no
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+              oasys_cv_prog_gcc_string_broken=yes
+
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+        ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $oasys_cv_prog_gcc_string_broken" >&5
+echo "${ECHO_T}$oasys_cv_prog_gcc_string_broken" >&6
+
+    if test $oasys_cv_prog_gcc_string_broken = yes ; then
+        { { echo "$as_me:$LINENO: error: broken std::string -- upgrade compiler" >&5
+echo "$as_me: error: broken std::string -- upgrade compiler" >&2;}
+   { (exit 1); exit 1; }; }
     fi
 
 
