be a little smarter about how we do checks for tcl and db so it first checks for the header, and then for the library

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2999,12 +2999,69 @@ echo "$as_me: error: cannot configure without tcl" >&2;}
     for ac_tcllibdir in $ac_tcllibdirs; do
     for ac_tcllib in tcl tcl$ac_tclver; do
 
-        echo "$as_me:$LINENO: checking for tcl (version $ac_tclver) in $ac_tclincdir, $ac_tcllibdir, -l$ac_tcllib" >&5
-echo $ECHO_N "checking for tcl (version $ac_tclver) in $ac_tclincdir, $ac_tcllibdir, -l$ac_tcllib... $ECHO_C" >&6
-
         ac_tclver_major=`echo $ac_tclver | cut -d . -f1`
 	ac_tclver_minor=`echo $ac_tclver | cut -d . -f2`
 	CPPFLAGS="$ac_save_CPPFLAGS -I$ac_tclincdir"
+	LDFLAGS="$ac_save_LDFLAGS"
+	LIBS="$ac_save_LIBS"
+
+					        echo "$as_me:$LINENO: checking for tcl.h (version $ac_tclver) in $ac_tclincdir" >&5
+echo $ECHO_N "checking for tcl.h (version $ac_tclver) in $ac_tclincdir... $ECHO_C" >&6
+
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                #include <tcl.h>
+
+                #if (TCL_MAJOR_VERSION != ${ac_tclver_major}) || \
+                    (TCL_MINOR_VERSION != ${ac_tclver_minor})
+                #error "incorrect version"
+                #endif
+
+int
+main ()
+{
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+              echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+              echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+              break 2
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+        echo "$as_me:$LINENO: checking for tcl library in $ac_tcllibdir, -l$ac_tcllib" >&5
+echo $ECHO_N "checking for tcl library in $ac_tcllibdir, -l$ac_tcllib... $ECHO_C" >&6
 	LDFLAGS="$ac_save_LDFLAGS -L$ac_tcllibdir"
 	LIBS="$ac_save_LIBS -l$ac_tcllib"
 
@@ -3147,16 +3204,15 @@ fi;
     for ac_dblibdir in $ac_dblibdirs; do
     for ac_dblib    in db_cxx-$ac_dbver; do
 
-        echo "$as_me:$LINENO: checking for Berkeley DB header (version $ac_dbver) in $ac_dbincdir" >&5
-echo $ECHO_N "checking for Berkeley DB header (version $ac_dbver) in $ac_dbincdir... $ECHO_C" >&6
-
         ac_dbver_major=`echo $ac_dbver | cut -d . -f1`
 	ac_dbver_minor=`echo $ac_dbver | cut -d . -f2`
 	CPPFLAGS="$ac_save_CPPFLAGS -I$ac_dbincdir"
 	LDFLAGS="$ac_save_LDFLAGS"
 	LIBS="$ac_save_LIBS"
 
-						cat >conftest.$ac_ext <<_ACEOF
+					        echo "$as_me:$LINENO: checking for Berkeley DB header (version $ac_dbver) in $ac_dbincdir" >&5
+echo $ECHO_N "checking for Berkeley DB header (version $ac_dbver) in $ac_dbincdir... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -3274,7 +3330,28 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
     LIBS="$ac_save_LIBS"
 
     if test x$dtn_cv_path_db_h = x ; then
-        AC_DB_HELP
+
+cat <<EOF
+
+Configure error with Berkeley DB...
+
+If your installed version is not one of $dbversions, you may
+have to specify it with --with-dbver.
+
+If your installation is in a non-standard path, you can specify
+it with --with-db=DIR.
+
+To download the latest version, go to http://www.sleepycat.com
+To build and install to /usr/local/BerkeleyDB-<version>:
+
+# cd <db_download_dir>/build_unix
+# ../dist/configure --enable-cxx
+# make
+# make install
+
+EOF
+
+
         { { echo "$as_me:$LINENO: error: can't find usable Berkeley DB installation" >&5
 echo "$as_me: error: can't find usable Berkeley DB installation" >&2;}
    { (exit 1); exit 1; }; }
@@ -3292,8 +3369,7 @@ echo "$as_me: error: can't find usable Berkeley DB installation" >&2;}
 
     LIBS="$LIBS -l$dtn_cv_lib_db"
 
-    fi # db_enabled
-
+    fi # if DB_ENABLED
 
 
 
@@ -6522,13 +6598,10 @@ done
           ac_config_headers="$ac_config_headers auto.config.h:auto.config.h.in"
 
 
-if test ! -f oasys/Rules.make ; then
-    echo "Configuring oasys library..."
-              ac_config_files="$ac_config_files oasys/Rules.make"
+          ac_config_files="$ac_config_files oasys/Rules.make"
 
-              ac_config_files="$ac_config_files oasys/config.h"
+          ac_config_files="$ac_config_files oasys/config.h"
 
-fi
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -7647,10 +7720,10 @@ echo "  Debug: $DEBUG"
 echo "  Optimize: $OPTIMIZE"
 echo "  Static: $STATIC"
 echo " "
-
-echo "Storage packages:"
+echo "External packages:"
+echo "  tcl: $oasys_cv_path_tcl_h/tcl.h $oasys_cv_path_tcl_lib/lib -l$oasys_cv_lib_tcl"
 if test $DB_ENABLED = 1 ; then
-  echo "  db: $dtn_cv_path_db_h/db.h $dtn_cv_path_db_lib/lib$dtn_cv_lib_db"
+  echo "  db: $dtn_cv_path_db_h/db.h $dtn_cv_path_db_lib -l$dtn_cv_lib_db"
 fi
 if test $POSTGRES_ENABLED = 1 ; then
   echo "  postgres: $dtn_cv_path_postgres_h/libpq-fe.h -L $dtn_cv_path_postgres_lib -lpq"
