more logic for finding a berkeley db installation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -297,39 +297,75 @@ else
 fi
 
 #
-# Find the berkeley db library
+# Find the berkeley db library (version 4.2)
+#
+dbver=4.2
+
+#
+# check if the user doesn't want berkeley db at all
 #
 if [ "$dbdir" = "none" ]; then
   # XXX/demmer do something
   exit 1
-else
-  #
-  # check the supplied (or system) directory
-  #
-  if [ "$dbdir" = "" ]; then
-	dbdir=/usr
-  fi
+#
+# check the supplied directory if the user gave us one
+#
+elif [ "$dbdir" != "" ]; then
+    if [ -r $dbdir/include/db.h -a  \
+	 -r $dbdir/include/db_cxx.h ] 
+    then
+        dbincdir=-I$dbdir/include
+    else
+	echo "can't find db.h and/or db_cxx.h in $dbdir/include"
+	exit 1
+    fi
 
-  if   [ ! -r $dbdir/include/db.h ] ; then
-	echo "can't find db.h in $dbdir/include"
-  	exit 1
-  elif   [ ! -r $dbdir/include/db_cxx.h ] ; then
-	echo "can't find db_cxx.h in $dbdir/include"
-  	exit 1
-  else
-	dbincdir=-I$dbdir/include
-  fi
-
-  if   [ ! -r $dbdir/lib/libdb.$libext ] ; then
-	echo "can't find libdb.$libext in $dbdir"
-  	exit 1
-  elif [ ! -r $dbdir/lib/libdb_cxx.$libext ] ; then
-	echo "can't find libdb_cxx.$libext in $dbdir"
-  	exit 1
-  else
+    if [ -r $dbdir/lib/libdb-$dbver.$libext -a \
+         -r $dbdir/lib/libdb_cxx-$dbver.$libext ] ; 
+    then
 	dblibdir=-L$dbdir/lib
-	dblib="-ldb -ldb_cxx"
-  fi
+	dblib="-ldb-$dbver -ldb_cxx-$dbver"
+    else
+	echo "can't find libdb-$dbver.$libext and/or libdb_cxx-$dbver.$libext in $dbdir/lib"
+	exit 1
+    fi
+#
+# otherwise, check for a system installation
+#
+else
+    dbdirs="/usr /usr/local/BerkeleyDB.$dbver"
+    for dbdir in $dbdirs; do
+    	if [ -r $dbdir/include/db.h -a  \
+	     -r $dbdir/include/db_cxx.h ]
+    	then
+	    grep DB_VERSION_STRING $dbdir/include/db.h | grep $dbver > /dev/null
+	    if [ $? = 0 ]; then
+	        dbincdir=-I$dbdir/include
+        	break
+ 	    fi
+	fi
+    done
+
+    if [ "$dbincdir" = "" ]; then
+       echo "can't find db.h and/or db_cxx.h in include directories (tried $dbdirs)"
+       exit 1
+    fi
+
+    dblib=libdb-$dbver.$libext
+    dbcxxlib=libdb_cxx-$dbver.$libext
+    for dbdir in $dbdirs; do
+	if [ -r $dbdir/lib/$dblib -a -r $dbdir/lib/$dbcxxlib ] ; then
+	    if [ $dbdir != "/usr" ]; then
+	    	dblibdir=-L$dbdir/lib
+            fi
+ 	    dblib="-ldb-$dbver -ldb_cxx-$dbver"
+	    break
+        fi
+    done
+    if [ "$dblibdir" = "" ]; then
+ 	echo "can't find $dblib and/or $dbcxxlib in lib directories (tried $dbdirs)"
+ 	exit 1
+    fi
 fi
 
 if [ $target == "arm" -o $target == "cerfcube" -o $target == "arm+apps" ]; then
