* add autoconf tests and a compatibility shim to make tclreadline   work on BSD-derived systems (such as MacOSX) which implement   libreadline using the libedit wrappers

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8699,16 +8699,90 @@ echo "$as_me:$LINENO: result: $ac_cv_search_readline" >&5
 echo "${ECHO_T}$ac_cv_search_readline" >&6
 if test "$ac_cv_search_readline" != no; then
   test "$ac_cv_search_readline" = "none required" || LIBS="$ac_cv_search_readline $LIBS"
-  oasys_have_readline=1
+  TCLREADLINE_ENABLED=1
 else
-  oasys_have_readline=0
+  TCLREADLINE_ENABLED=0
 fi
 
 
-    if test $oasys_have_readline = 1 ; then
-        TCLREADLINE_ENABLED=1
+                    if test $TCLREADLINE_ENABLED = 1 ; then
+         echo "$as_me:$LINENO: checking whether readline is GNU readline or BSD editline" >&5
+echo $ECHO_N "checking whether readline is GNU readline or BSD editline... $ECHO_C" >&6
+if test "${oasys_cv_readline_is_editline+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char rl_extend_line_buffer ();
+int
+main ()
+{
+rl_extend_line_buffer ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  oasys_cv_readline_is_editline=GNU
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+oasys_cv_readline_is_editline=editline
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $oasys_cv_readline_is_editline" >&5
+echo "${ECHO_T}$oasys_cv_readline_is_editline" >&6
+        if test $oasys_cv_readline_is_editline = editline ; then
+
+cat >>confdefs.h <<_ACEOF
+#define READLINE_IS_EDITLINE 1
+_ACEOF
+
+        fi
+
+		echo "$as_me:$LINENO: checking whether tclreadline support was found" >&5
+echo $ECHO_N "checking whether tclreadline support was found... $ECHO_C" >&6
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
     else
-        TCLREADLINE_ENABLED=0
+		echo "$as_me:$LINENO: checking whether tclreadline support was found" >&5
+echo $ECHO_N "checking whether tclreadline support was found... $ECHO_C" >&6
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
     fi
 
     fi # ac_tclreadline != no
