fix berkeley db configure to not look for a file and to handle cases where db.h redefines symbol names

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2970,8 +2970,7 @@ echo "$as_me: error: cannot configure without tcl" >&2;}
     fi
 
                 if test ! x$oasys_cv_path_tcl_h = x ; then
-        echo "checking for tcl installation... (cached) \
-	      ($oasys_cv_path_tcl_h/tcl.h, $oasys_cv_path_tcl_lib -l$oasys_cv_lib_tcl)"
+        echo "checking for tcl installation... (cached) $oasys_cv_path_tcl_h/tcl.h, $oasys_cv_path_tcl_lib -l$oasys_cv_lib_tcl"
     else
 
     oasys_cv_path_tcl_h=
@@ -3092,7 +3091,7 @@ echo "$as_me: error: can't find usable tcl.h" >&2;}
     LIBS="$LIBS -l$oasys_cv_lib_tcl"
 
 
-    ac_dbver='4.3 4.2'
+    ac_dbvers='4.3 4.2'
     ac_dbdir='system'
 
 
@@ -3106,7 +3105,7 @@ fi;
 # Check whether --with-dbver or --without-dbver was given.
 if test "${with_dbver+set}" = set; then
   withval="$with_dbver"
-  ac_dbver=$withval
+  ac_dbvers=$withval
 fi;
 
                 if test x$ac_dbdir = xnone ; then
@@ -3114,163 +3113,50 @@ fi;
     else
     DB_ENABLED=1
 
-                    if test x$dtn_cv_path_db_h = x ; then
-        echo "checking for Berkeley DB header file..."
+                if test ! x$dtn_cv_path_db_h = x ; then
+        echo "checking for Berkeley DB installation... (cached) $dtn_cv_path_db_h/db.h, $dtn_cv_path_db_lib -l$dtn_cv_lib_db"
+    else
+
+    dtn_cv_path_db_h=
+
+    ac_save_CPPFLAGS="$CPPFLAGS"
+    ac_save_LDFLAGS="$LDFLAGS"
+    ac_save_LIBS="$LIBS"
 
     if test ! x"$ac_dbdir" = x"system" ; then
         ac_dbincdirs=$ac_dbdir/include
     else
         ac_dbincdirs="/usr/include /usr/local/include/db4"
-        for dbver in $ac_dbver ; do
-            ac_dbincdirs="$ac_dbincdirs /usr/include/db$dbver"
-            ac_dbincdirs="$ac_dbincdirs /usr/local/BerkeleyDB.$dbver/include"
+	for ac_dbver in $ac_dbvers ; do
+           ac_dbincdirs="$ac_dbincdirs /usr/include/db$ac_dbver"
+           ac_dbincdirs="$ac_dbincdirs /usr/local/BerkeleyDB.$ac_dbver/include"
         done
     fi
 
-    if test "${dtn_cv_path_db_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-      dtn_cv_path_db_h=
-      for ac_dbincdir in $ac_dbincdirs; do
-          as_ac_File=`echo "ac_cv_file_$ac_dbincdir/db.h" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $ac_dbincdir/db.h" >&5
-echo $ECHO_N "checking for $ac_dbincdir/db.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$ac_dbincdir/db.h"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-
-              for dbver in $ac_dbver ; do
-  	      echo "$as_me:$LINENO: checking whether $ac_dbincdir/db.h is version $dbver" >&5
-echo $ECHO_N "checking whether $ac_dbincdir/db.h is version $dbver... $ECHO_C" >&6
-                egrep "DB_VERSION_STRING.*$dbver" $ac_dbincdir/db.h \
-  		    >/dev/null 2>/dev/null
-                if test $? = 0 ; then
-  	          echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-  	          as_ac_File=`echo "ac_cv_file_$ac_dbincdir/db_cxx.h" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $ac_dbincdir/db_cxx.h" >&5
-echo $ECHO_N "checking for $ac_dbincdir/db_cxx.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$ac_dbincdir/db_cxx.h"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-
-   	              dtn_cv_path_db_h=$ac_dbincdir
-    	              break 2
-
-fi
-
-                else
-                  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-                fi
-              done
-
-fi
-
-      done
-
-fi
-
-
-    if test x$dtn_cv_path_db_h = x ; then
-
-cat <<EOF
-
-Configure error with Berkeley DB...
-
-If your installed version is not one of $dbversions, you may
-have to specify it with --with-dbver.
-
-If your installation is in a non-standard path, you can specify
-it with --with-db=DIR.
-
-To download the latest version, go to http://www.sleepycat.com
-To build and install to /usr/local/BerkeleyDB-<version>:
-
-# cd <db_download_dir>/build_unix
-# ../dist/configure --enable-cxx
-# make
-# make install
-
-EOF
-
-
-        { { echo "$as_me:$LINENO: error: can't find usable db.h" >&5
-echo "$as_me: error: can't find usable db.h" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-
+    if test ! x"$ac_dbdir" = x"system" ; then
+        ac_dblibdirs="$ac_dbdir/lib"
     else
-        echo "checking for Berkeley DB header file... (cached) $dtn_cv_path_db_h/db.h"
+        ac_dblibdirs="/usr/lib /usr/local/lib"
+	for ac_dbver in $ac_dbvers ; do
+           ac_dblibdirs="$ac_dblibdirs /usr/local/BerkeleyDB.$ac_dbver/lib"
+        done
     fi
 
-    if test ! x$dtn_cv_path_db_h = /usr/include ; then
-        CPPFLAGS="$CPPFLAGS -I$dtn_cv_path_db_h"
-    fi
+    for ac_dbver    in $ac_dbvers ; do
+    for ac_dbincdir in $ac_dbincdirs; do
+    for ac_dblibdir in $ac_dblibdirs; do
+    for ac_dblib    in db_cxx-$ac_dbver; do
 
-                if test x$dtn_cv_lib_db = x ; then
-        echo "checking for Berkeley DB library..."
+        echo "$as_me:$LINENO: checking for Berkeley DB header (version $ac_dbver) in $ac_dbincdir" >&5
+echo $ECHO_N "checking for Berkeley DB header (version $ac_dbver) in $ac_dbincdir... $ECHO_C" >&6
 
-    if test "${dtn_cv_lib_db+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
+        ac_dbver_major=`echo $ac_dbver | cut -d . -f1`
+	ac_dbver_minor=`echo $ac_dbver | cut -d . -f2`
+	CPPFLAGS="$ac_save_CPPFLAGS -I$ac_dbincdir"
+	LDFLAGS="$ac_save_LDFLAGS"
+	LIBS="$ac_save_LIBS"
 
-        ac_save_LDFLAGS=$LDFLAGS
-
-				case $dtn_cv_path_db_h in
-  	/usr/include/*)
-	    dtn_cv_path_db_lib=/usr/lib
-	    ;;
-
-	/usr/local/include/db4)
-	    dtn_cv_path_db_lib=/usr/local/lib
-	    ;;
-
-	*)
-            dtn_cv_path_db_lib=`echo $dtn_cv_path_db_h | sed 's,/include,,'`/lib
-	    ;;
-	esac
-
-        LDFLAGS="-L$dtn_cv_path_db_lib"
-
-        for dbver in $ac_dbver; do
-           dtn_cv_lib_db=db_cxx-$dbver
-           as_ac_Lib=`echo "ac_cv_lib_$dtn_cv_lib_db''_db_create" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for db_create in -l$dtn_cv_lib_db" >&5
-echo $ECHO_N "checking for db_create in -l$dtn_cv_lib_db... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Lib+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-l$dtn_cv_lib_db  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
+						cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -3278,17 +3164,18 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char db_create ();
+                #include <db.h>
+
+                #if (DB_VERSION_MAJOR != ${ac_dbver_major}) || \
+                    (DB_VERSION_MINOR != ${ac_dbver_minor})
+                #error "incorrect version"
+                #endif
+
 int
 main ()
 {
-db_create ();
+
+
   ;
   return 0;
 }
@@ -3305,69 +3192,108 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  eval "$as_ac_Lib=yes"
+
+	      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-eval "$as_ac_Lib=no"
+
+              echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	      break 2
+
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
-if test `eval echo '${'$as_ac_Lib'}'` = yes; then
-  break
+
+	LDFLAGS="$ac_save_LDFLAGS -L$ac_dblibdir"
+	LIBS="$ac_save_LIBS -l$ac_dblib"
+
+        echo "$as_me:$LINENO: checking for Berkeley DB library in $ac_dblibdir, -l$ac_dblib" >&5
+echo $ECHO_N "checking for Berkeley DB library in $ac_dblibdir, -l$ac_dblib... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                #include <db.h>
+
+int
+main ()
+{
+
+	        DB *db;
+                db_create(&db, NULL, 0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+              echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+              dtn_cv_path_db_h=$ac_dbincdir
+              dtn_cv_path_db_lib=$ac_dblibdir
+              dtn_cv_lib_db=$ac_dblib
+              break 4
+
 else
-  dtn_cv_lib_db=
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+              echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
 fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+    done
+    done
+    done
 
-        done
+    CPPFLAGS="$ac_save_CPPFLAGS"
+    LDFLAGS="$ac_save_LDFLAGS"
+    LIBS="$ac_save_LIBS"
 
-        LDFLAGS=$ac_save_LDFLAGS
-
-fi
-
-
-    if test x$dtn_cv_lib_db = x ; then
-
-cat <<EOF
-
-Configure error with Berkeley DB...
-
-If your installed version is not one of $dbversions, you may
-have to specify it with --with-dbver.
-
-If your installation is in a non-standard path, you can specify
-it with --with-db=DIR.
-
-To download the latest version, go to http://www.sleepycat.com
-To build and install to /usr/local/BerkeleyDB-<version>:
-
-# cd <db_download_dir>/build_unix
-# ../dist/configure --enable-cxx
-# make
-# make install
-
-EOF
-
-
-        { { echo "$as_me:$LINENO: error: can't find usable db library" >&5
-echo "$as_me: error: can't find usable db library" >&2;}
+    if test x$dtn_cv_path_db_h = x ; then
+        AC_DB_HELP
+        { { echo "$as_me:$LINENO: error: can't find usable Berkeley DB installation" >&5
+echo "$as_me: error: can't find usable Berkeley DB installation" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
-    else
-        echo "checking for Berkeley DB library... (cached) -l$dtn_cv_lib_db"
+    fi
+
+    if test ! $dtn_cv_path_db_h = /usr/include ; then
+        CPPFLAGS="$CPPFLAGS -I$dtn_cv_path_db_h"
     fi
 
     if test ! $dtn_cv_path_db_lib = /usr/lib ; then
         LDFLAGS="$LDFLAGS -L$dtn_cv_path_db_lib"
     fi
+
     LIBS="$LIBS -l$dtn_cv_lib_db"
 
-    fi # if DB_ENABLED
+    fi # db_enabled
+
 
 
 
