patch in Bowei's changes from the bowei-bf-bbn-branch: * Add a thread local storage utility class to oasys that uses   pthread_setspecific * Use the TLS class to implement a LockDebugging class to help ensure   that only a specific set of locks are held by the thread * Add a TimeScope class to log the time the current scope takse

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -872,6 +872,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-debug         compile with debugging turned off
   --enable-debug-memory   enable memory debugging
+  --disable-debug-locking disable lock debugging
   --disable-optimize      compile with optimization turned off
   --enable-profile        compile with profiling
   --enable-static         statically link all binaries
@@ -2667,6 +2668,27 @@ echo "${ECHO_T}$debug_memory" >&6
 
 cat >>confdefs.h <<_ACEOF
 #define OASYS_DEBUG_MEMORY_ENABLED 1
+_ACEOF
+
+    fi
+
+                    # Check whether --enable-debug_locking or --disable-debug_locking was given.
+if test "${enable_debug_locking+set}" = set; then
+  enableval="$enable_debug_locking"
+  debug_locking=$enableval
+else
+  debug_locking=$debug
+fi;
+
+    echo "$as_me:$LINENO: checking whether to compile with lock debugging (default $debug)" >&5
+echo $ECHO_N "checking whether to compile with lock debugging (default $debug)... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $debug_locking" >&5
+echo "${ECHO_T}$debug_locking" >&6
+
+    if test $debug_locking = yes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define OASYS_DEBUG_LOCKING_ENABLED 1
 _ACEOF
 
     fi
@@ -4839,6 +4861,136 @@ else
 echo "$as_me: error: can't find required library function (pthread_yield or sched_yield)" >&2;}
    { (exit 1); exit 1; }; }
 fi
+
+fi
+
+    echo "$as_me:$LINENO: checking for library containing pthread_setspecific" >&5
+echo $ECHO_N "checking for library containing pthread_setspecific... $ECHO_C" >&6
+if test "${ac_cv_search_pthread_setspecific+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_pthread_setspecific=no
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pthread_setspecific ();
+int
+main ()
+{
+pthread_setspecific ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_pthread_setspecific="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_pthread_setspecific" = no; then
+  for ac_lib in pthread; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pthread_setspecific ();
+int
+main ()
+{
+pthread_setspecific ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_pthread_setspecific="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_pthread_setspecific" >&5
+echo "${ECHO_T}$ac_cv_search_pthread_setspecific" >&6
+if test "$ac_cv_search_pthread_setspecific" != no; then
+  test "$ac_cv_search_pthread_setspecific" = "none required" || LIBS="$ac_cv_search_pthread_setspecific $LIBS"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_PTHREAD_SETSPECIFIC 1
+_ACEOF
 
 fi
 
