configure script cleanup

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,41 +1,5 @@
 #!/bin/sh
 #
-# IMPORTANT:  READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
-# By downloading, copying, installing or using the software you agree to this 
-# license.  If you do not agree to this license, do not download, install,
-# copy or use the software.
-#
-# Copyright (c) 2003, The MITRE Corporation
-# All rights reserved.
-# 
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are 
-# met:
-# 
-# Redistributions of source code must retain the above copyright notice,
-# this list of conditions and the following disclaimer.  Redistributions 
-# in binary form must reproduce the above copyright notice, this list of 
-# conditions and the following disclaimer in the documentation and/or 
-# other materials provided with the distribution.
-# 
-# Neither the name of The MITRE Corporation nor the names of its 
-# contributors may be used to endorse or promote products derived from 
-# this software without specific prior written permission.
-# 
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
-# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
-# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
-# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
-# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
-# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
-# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
-# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
-# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
-# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
-# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-# 
-# $Id$
-#
 
 #
 # Before anything else, check for configure --verbose
@@ -49,12 +13,24 @@ for ac_option do
    esac
 done
 
-##############
 #
-# CFLAGS
-##############
+# Figure out srcdir based on the path to the configure script
 #
-#
+confscript=$0
+srcdir=`echo "$confscript" | sed 's%[\\/][^\\/][^\\/]*$%%'`
+if test "$srcdir" = "$confscript" ; then
+   srcdir=.
+fi
+
+if ! test -r "$srcdir/Rules.make.in" ; then
+   echo "Can't find Rules.make.in in srcdir $srcdir"
+   exit 1
+fi
+
+if ! test "$srcdir" = "." ; then
+   echo "XXX/demmer support non-local srcdir"
+   exit 1
+fi
 
 #########
 #
@@ -67,13 +43,6 @@ done
 #
 
 target=native
-
-exec_prefix='/usr/local/DTN'
-bindir='${exec_prefix}/bin'
-sbindir='${exec_prefix}/sbin'
-libdir='${exec_prefix}/lib'
-incdir='${exec_prefix}/include'
-mandir='/usr/local/man/manl'
 static=''
 allstatic=''
 
@@ -81,6 +50,7 @@ allstatic=''
 # Defaults
 #
 cc='gcc'
+ccver='auto'
 depflags=''
 make_static='n'
 debug='-g'
@@ -98,7 +68,7 @@ libs=
 staticlibs=''
 
 tclver='8.3'
-tcldir=''
+tcldir='system'
 tclincdir=''
 tcllibdir=''
 tcllib=''
@@ -157,16 +127,6 @@ do
   -dynamic | --dynamic)
     make_static=n ;;
 
-  -exec-prefix | --exec-prefix | -ep)
-    ac_prev=exec_prefix ;;
-  -exec-prefix=* | --exec-prefix=* | -ep=*)
-    exec_prefix="$ac_optarg" ;;
-
-  -mandir | --mandir | -md)
-    ac_prev=mandir ;;
-  -mandir=* | --mandir=* | -md=*)
-    mandir="$ac_optarg" ;;
-
   -enable-debug | --enable-debug)
     debug='-g' ;;
   -disable-debug | --disable-debug)
@@ -185,6 +145,11 @@ do
     ac_prev=with-cc ;;
   -with-gcc=* | --with-gcc=* | -with-cc=* | --with-cc=*)
     cc="$ac_optarg" ;;
+
+  -with-gccver | --with-gccver | -with-ccver | --with-ccver)
+    ac_prev=with-cc ;;
+  -with-gccver=* | --with-gccver=* | -with-ccver=* | --with-ccver=*)
+    ccver="$ac_optarg" ;;
 
   -with-tcl | --with-tcl)
     ac_prev=with-tcl ;;
@@ -216,37 +181,31 @@ do
   -with-mysql=* | --with-mysql=*)
     mysqldir="$ac_optarg" ;;
 
-  -with-capriccio-pthread | --with-capriccio-pthread)
-    ac_prev=with-capriccio-pthread ;;
-  -with-capriccio-pthread=* | --with-capriccio-pthread=*)
-    capriccio=y
-    capricciodir="$ac_optarg" ;;
-
   -help | --help | -h)
     cat <<EOF
 Usage: configure [options]
 Options [defaults in brackets after descriptions]
 Directory and file names:
-  --exec-prefix=EPREFIX           install architecture-independent files in PREFIX
-                                  [$exec_prefix]
   --target=TARGET                 Configure for TARGET.  Valid targets are 'native'
                                   and 'arm' [$target]
-  --static                        Build static objects; do not use dynamic link libraries
-  --mandir=MANUAL_DIR             Install man pages here [$mandir]
+  --static                        Build static objects and libraries (default)
+  --dynamic                       Build using dynamic link libraries
 Features
-     debug			  Include '-g' in the CFLAGS.
-     optimize			  Include '-O' in the CFLAGS.
-
-  --disable-FEATURE
-  --enable-FEATURE[=ARG]
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --disable-debug         compile with debugging turned off
+  --disable-optimize      compile with optimization turned off
 Packages
-  --with-cc=GCC			  Version of the C/C++ compiler to use
-  --with-tcl=DIR		  Location of a tcl installation (default system)
+  --with-cc=GCC		  Version of the C/C++ compiler to use
+  --with-ccver=VER        Version of the C/C++ compiler to use
+  --with-tcl=DIR          Location of the tcl installation [$tcldir]
+  --with-tclver=VERSION   Version of tcl to use [$tclver]
 
 Storage Options:  
-  --with-db=DIR			  Location of a Berkeley DB installation (default system)
-  --with-postgres=DIR		  Location of a Postgres installation (default none)
-  --with-mysql=DIR		  Location of a Mysql installation (default none)
+  --with-db=DIR			  Location of a Berkeley DB installation [$dbdir]
+  --with-dbver=VERSION		  Berkeley DB version to link with [$dbver]
+  --with-postgres=DIR		  Location of a Postgres installation [$postgresdir]
+  --with-mysql=DIR		  Location of a Mysql installation [$mysqldir]
 
   (set DIR=none   to disable the option)
   (set DIR=system to search default locations)
@@ -326,26 +285,35 @@ case "$ccver" in
 esac
 
 #
-# assume that if we're using gcc-xxx, we also want g++-xxx
+# Assume that if we're using gcc-xxx, we also want g++-xxx
 #
 cpp=`echo $cc | sed 's/cc/++/'`
 
+#
+# Set options to build statically
+#
 case "$make_static" in
     yes | y | true | t)
+    echo "static linking not supported in this release"a
+    exit 1
     static="-static"
     allstatic="-all-static"
-    libext=a
     ;;
 
     *)
-    libext=so
     ;;
 esac
 
 #
+# Set platform-specific options for library extensions
+#
+libext=a
+shlibext=so
+
+#
 # Find the tcl library
 #
-if [ ! "$tcldir" = "" ]; then
+if [ ! "$tcldir" = "system" ]; then
   #
   # Make sure the directory the user specified is ok
   #
@@ -356,12 +324,16 @@ if [ ! "$tcldir" = "" ]; then
 	exit 1
   fi
 
-  if   [ -r $tcldir/lib/libtcl.$libext ]; then
+  if   [ -r $tcldir/lib/libtcl.$libext -o \
+	 -r $tcldir/lib/libtcl.$shlibext ] ; then
 	tcllibdir=-L$tcldir/lib
 	tcllib=-ltcl
-  elif [ -r $tcldir/lib/libtcl$tclver.$libext ]; then
+
+  elif [ -r $tcldir/lib/libtcl$tclver.$libext -o \
+	 -r $tcldir/lib/libtcl$tclver.$shlibext ]; then
 	tcllibdir=-L$tcldir/lib
 	tcllib=-ltcl$tclver
+
   else
 	echo "can't find libtcl.$libext or libtcl$tclver.$libext in $tcldir"
 	exit 1
@@ -373,17 +345,23 @@ else
   #
   if [ -r /usr/include/tcl.h ]; then
 	tclincdir=
+
   elif [ -r /usr/include/tcl$tclver/tcl.h ]; then
 	tclincdir=-I/usr/include/tcl$tclver
+
   else
 	echo "can't find usable tcl.h"
 	exit 1
   fi
 
-  if   [ -r /usr/lib/libtcl.$libext ]; then
+  if   [ -r /usr/lib/libtcl.$libext -o \
+	 -r /usr/lib/libtcl.$shlibext ]; then
 	tcllib=-ltcl
-  elif [ -r /usr/lib/libtcl$tclver.$libext ]; then
+
+  elif [ -r /usr/lib/libtcl$tclver.$libext -o \
+	 -r /usr/lib/libtcl$tclver.$shlibext ]; then
 	tcllib=-ltcl$tclver
+
   else
 	echo "can't find usable libtcl.$libext"
 	exit 1
@@ -472,19 +450,6 @@ else
     fi
   fi
 fi
-
-if [ $target == "arm" -o $target == "cerfcube" -o $target == "arm+apps" ]; then
-    # XXX/demmer is this really needed???
-	exec_prefix=`pwd`/Stage
-	bindir='${exec_prefix}/bin'
-	sbindir='${exec_prefix}/sbin'
-	libdir='${exec_prefix}/lib'
-	mandir='${exec_prefix}/man/manl'
-	idir='${exec_prefix}/include'
-	cflags='-g -Wall -DUSE_DB -DDB_PKG_SLEEPYCAT_$db_version -D_REENTRANT'
-fi
-
-
 
 #
 # Find the postgres dlibrary
@@ -604,26 +569,6 @@ else
    fi
 fi
 
-if [ "$capriccio" = "y" ]; then
-	if [ ! $make_static = 'y' ]; then
-		echo "capriccio can only be linked statically"
-		exit 1
-	fi
-
-	if [ ! -r $capricciodir/src/include/pthread.h ]; then
-		echo "can't find pthread.h in $capricciodir/src/include"
-		exit 1
-	fi
-	pthreadincdir=-I$capricciodir/src/include
-	
-	if [ ! -r $capricciodir/src/lib/libpthread.a ]; then
-		echo "can't find libpthread.a in $capricciodir/lib"
-		exit 1
-	fi
-	pthreadlib=''
-	pthreadstaticlib=$capricciodir/src/lib/libpthread.a
-fi
-
 #
 # Make sure there's at least one valid storage option
 #
@@ -665,37 +610,26 @@ done
 # Tack on the dependency libs if we're building statically
 #
 if [ "$make_static" = "y" ]; then
-	libs="$libs -ldl -lssl -lcrypto -lkrb5 -lcrypt -lresolv"\
+	libs="$libs -ldl -lssl -lcrypto -lkrb5 -lcrypt -lresolv" \
 	    "-lnsl -lz -lk5crypto -lcom_err"
 fi
 
+echo "DTN2 configure state:"
 echo "Target/Tools:"
 echo "  TARGET is: $target"
 echo "  CC is: $cc"
 echo "  CPP is: $cpp"
 echo " "
 echo "Options:"
-echo "  TARGET is: $target"
 echo "  Debug: $debug"
 echo "  Optimize: $optimize"
 echo "  Static: $make_static"
-echo " "
-echo "Directories"
-echo "  exec_prefix: $exec_prefix"
-echo "  bindir:  $bindir"
-echo "  sbindir: $sbindir"
-echo "  libdir:  $libdir"
-echo "  mandir:  $mandir"
-echo "  incdir:  $incdir"
 echo " "
 echo "Packages"
 echo "  tcl: $tclincdir $tcllibdir $tcllib"
 echo "  db: $dbincdir $dblibdir $dblib"
 echo "  postgres: $postgresincdir $postgreslibdir $postgreslib"
 echo "  mysql: $mysqlincdir $mysqllibdir $mysqllib"
-if [ "$capriccio" = 'y' ]; then
-echo "  capriccio: $pthreadincdir $pthreadlibdir $pthreadlib $pthreadstaticlib"
-fi
 
 rm -f Rules.make
 echo > Rules.make <<EOF
@@ -708,16 +642,9 @@ echo > Rules.make <<EOF
 EOF
 
 sed -e "
-s%@EXEC_PREFIX@%$exec_prefix%g
+s%@SRCDIR@%$srcdir%g
 s%@CFLAGS@%$cflags%g
-s%@BINDIR@%$bindir%g
-s%@SBINDIR@%$sbindir%g
-s%@LIBDIR@%$libdir%g
-s%@MANDIR@%$mandir%g
-s%@INCDIR@%$incdir%g
-s%@TARGET@%$target%g
 s%@STATIC@%$static%g
-s%@ALLSTATIC@%$allstatic%g
 s%@CC@%$cc%g
 s%@CPP@%$cpp%g
 s%@DEPFLAGS@%$depflags%g
@@ -728,6 +655,7 @@ s%@INCDIRS@%$incdirs%g
 s%@LIBDIRS@%$libdirs%g
 s%@LIBS@%$libs%g
 s%@STATIC_LIBS@%$staticlibs%g
+s%@PTHREAD_FLAG@%$pthreadflag%g
 
 " Rules.make.in >> Rules.make
 chmod oag-w Rules.make
