* add built-in tclreadline support to oasys/DTN, extended with a   simple "eof" command to force it to break out of the readline loop * change the DTN2 shutdown command to just call exit_event_loop and   rely on the main thread in dtnd.cc to shut down everything else

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -885,6 +885,7 @@ Optional Packages:
                           none)
   --with-bluez            compile in bluetooth support (default try)
   --with-expat=DIR        location of an expat installation (default try)
+  --with-tclreadline      enable or disable tclreadline (default try)
 
 Some influential environment variables:
   CC          C compiler command
@@ -8548,6 +8549,175 @@ _ACEOF
     fi
 
     fi # ac_expatdir != no
+
+
+
+# Check whether --with-tclreadline or --without-tclreadline was given.
+if test "${with_tclreadline+set}" = set; then
+  withval="$with_tclreadline"
+  ac_tclreadline=$withval
+else
+  ac_tclreadline=try
+fi;
+
+    echo "$as_me:$LINENO: checking whether tclreadline support should be enabled" >&5
+echo $ECHO_N "checking whether tclreadline support should be enabled... $ECHO_C" >&6
+
+                if test "$ac_tclreadline" = no ; then
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    TCLREADLINE_ENABLED=0
+
+    else
+
+                if test "$ac_tclreadline" = try ; then
+       echo "$as_me:$LINENO: result: try" >&5
+echo "${ECHO_T}try" >&6
+    else
+       echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    fi
+
+                echo "$as_me:$LINENO: checking for library containing readline" >&5
+echo $ECHO_N "checking for library containing readline... $ECHO_C" >&6
+if test "${ac_cv_search_readline+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_readline=no
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char readline ();
+int
+main ()
+{
+readline ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_readline="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_readline" = no; then
+  for ac_lib in readline; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char readline ();
+int
+main ()
+{
+readline ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_readline="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_readline" >&5
+echo "${ECHO_T}$ac_cv_search_readline" >&6
+if test "$ac_cv_search_readline" != no; then
+  test "$ac_cv_search_readline" = "none required" || LIBS="$ac_cv_search_readline $LIBS"
+  oasys_have_readline=1
+else
+  oasys_have_readline=0
+fi
+
+
+    if test $oasys_have_readline = 1 ; then
+        TCLREADLINE_ENABLED=1
+    else
+        TCLREADLINE_ENABLED=0
+    fi
+
+    fi # ac_tclreadline != no
+
+
+cat >>confdefs.h <<_ACEOF
+#define TCLREADLINE_ENABLED $TCLREADLINE_ENABLED
+_ACEOF
+
 
 
 
